replicaCount: 1

image:
  registry: registry.oglimmer.com
  repository: easy-host
  tag: latest
  pullPolicy: Always

imagePullSecrets:
  - name: oglimmerregistrykey

serviceAccount:
  create: true
  name: ""

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  host: content.oglimmer.com
  tls:
    enabled: true
    secretName: tls-easy-host-ingress-dns
  certManager:
    enabled: true
    clusterIssuer: oglimmer-com-dns

resources:
  limits:
    cpu: 1000m
    memory: 768Mi
  requests:
    cpu: 250m
    memory: 384Mi

securityContext:
  runAsNonRoot: true
  runAsUser: 10001
  fsGroup: 10001

database:
  host: mariadb
  port: 3306
  name: easyhost
  username: easyhost
  password: easyhost

app:
  admin:
    username: admin
    password: changeme
  actuator:
    username: actuator
    password: changeme
  oidc:
    # Secret name containing keys: client-id, client-secret
    secretName: easy-host-oidc-secret
    issuerUrl: "https://id.oglimmer.de/realms/oglimmer"
    allowedUsers: "oglimmer@gmail.com"
  javaOpts: "-Xmx384m -Xms384m -XX:MaxMetaspaceSize=192m -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:MaxRAM=600m"
